name: Node + Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout código
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # 3️⃣ Instalar dependências
      - run: npm ci

      # 4️⃣ Rodar testes
      - run: npm test || echo "No tests configured"

      # 5️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7️⃣ Build e Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            lukinhas22/lucasapp:latest
            lukinhas22/lucasapp:${{ github.sha }}
